services:
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1
      interval: 10s
      timeout: 5s

  rest:
    image: dirscanner
    build: ./
    volumes:
      - ${DIRSCANNER_ROOT}:/scan:ro
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DIRSCANNER_ROOT=/scan
      - DIRSCANNER_DELAY_MINUTES=${DIRSCANNER_DELAY_MINUTES}
    depends_on:
      postgres:
        condition: service_healthy
